import { ADVANCE } from "../../ADVANCE/Advance.js";
import { CREATEUSERACCOUNT } from "../../FUNCTIONS/CreateUserAccount.js";
import { LOGINPAGE } from "./LoginPage.js";

const APPNAME=ADVANCE.LOGINAPPNAME;

APPNAME.innerHTML='Socilite';

const CREATEMESSAGE=ADVANCE.CREATEMESSAGE;

const USERNAMEINPUT=ADVANCE.CREATEACCOUNTUSERNAMEINPUT;

const EMAILINPUT=ADVANCE.CREATEEMAILINPUT;

const PASSWORDINPUT=ADVANCE.LOGINPASSWORDINPUT;

const CREATEINPUTDATE=ADVANCE.CREATEINPUTDATE;

const CREATEPHONENUMBER=ADVANCE.CREATEPHONENUMBER;

const CREATELOCATIONINPUT=ADVANCE.CREATELOCATIONINPUT;

const LOGINBUTTON=ADVANCE.LOGINACCOUNTBUTTON;

const CREATEACCOUNTBUTTON=ADVANCE.CREATEACCOUNTBUTTTON;



const CREATEACCOUNTPAGE=(DIV)=>{

    DIV.innerHTML='';

    DIV.append(APPNAME);

    DIV.append(CREATEMESSAGE);

    DIV.append(USERNAMEINPUT);

    DIV.append(EMAILINPUT);

    DIV.append(PASSWORDINPUT);

    DIV.append(CREATEINPUTDATE);

    DIV.append(CREATEPHONENUMBER);

    DIV.append(CREATELOCATIONINPUT);
    
    DIV.append(CREATEACCOUNTBUTTON);

    DIV.append(LOGINBUTTON);

    LOGINBUTTON.onclick=()=>{

        LOGINPAGE(DIV)

    };

    CREATEACCOUNTBUTTON.onclick=()=>{

        CREATEUSERACCOUNT(DIV,CREATEACCOUNTBUTTON,USERNAMEINPUT,EMAILINPUT,PASSWORDINPUT,CREATEINPUTDATE,CREATEPHONENUMBER,CREATELOCATIONINPUT,CREATEMESSAGE)

    }
     
}

export{CREATEACCOUNTPAGE};