import { ADVANCE } from "../../ADVANCE/Advance.js";
import { LOGINUSER } from "../../FUNCTIONS/LoginUser.js";
import { CREATEACCOUNTPAGE } from "./CreateAccountPage.js";

const APPNAME=ADVANCE.LOGINAPPNAME;

APPNAME.innerHTML='Socilite';

const LOGINMESSAGE=ADVANCE.LOGINMESSAGE;

const EMAILINPUT=ADVANCE.LOGINEMAILINPUT;

const PASSWORDINPUT=ADVANCE.LOGINPASSWORDINPUT;

const LOGINBUTTON=ADVANCE.LOGINACCOUNTBUTTON;

const CREATEACCOUNTBUTTON=ADVANCE.LOGINCREATEACCOUNTBUTTON;


const LOGINPAGE=(DIV)=>{

    DIV.innerHTML='';

    DIV.append(APPNAME);

    DIV.append(LOGINMESSAGE);

    DIV.append(EMAILINPUT);

    DIV.append(PASSWORDINPUT);

    DIV.append(LOGINBUTTON);

    DIV.append(CREATEACCOUNTBUTTON);

    CREATEACCOUNTBUTTON.onclick=()=>{

        CREATEACCOUNTPAGE(DIV);

    };

    LOGINBUTTON.onclick=()=>{

        LOGINUSER(DIV,EMAILINPUT,PASSWORDINPUT,LOGINBUTTON,LOGINMESSAGE)

    };
    
     
}

export{LOGINPAGE};